# Generated by Django 5.0.1 on 2024-01-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newdjango', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='country',
            new_name='function',
        ),
        migrations.RemoveField(
            model_name='member',
            name='image',
        ),
        migrations.RemoveField(
            model_name='member',
            name='salary',
        ),
    ]
